#Python Basics

##Topics

* 1. Basic Python: Basic data types, Functions


**Additional Libraries**

* 2. Numpy: Arrays, indexing, operations
* 3. Matplotlib: Basic plotting

**4. Assignment**


##Python Basics

Python is a general purpose, high-level, interpretive programming language. Easy to learn/code. Works like a pseudo-algorithm! 

Open source! Lots of other helper libraries that we can leverage.

Standard Library:  [Documentation](https://docs.python.org/3.7/library/stdtypes.html)

###Basic data types

####1. Numerical

In [ ]:
x = 3
print(x, type(x))

3 <class 'int'>


In [ ]:
x = 3.33
print(x, type(x))

3.33 <class 'float'>


In [ ]:
# Numerical operations

print(x + 1)    # Addition
print(x * 2)    # Multiplication
print(x ** 2)   # Exponentiation
print(x % 2)    # Modulus  

4.33
6.66
11.0889
1.33


In [ ]:
# Numerical assignments

x += 1
print(x)

4.33


####2. Booleans

In [ ]:
x = True
print(x, type(x))

True <class 'bool'>


In [ ]:
# Boolean operations


print (True and False)  # and
print (x or False)      # or
print (not x)           # not

False
True
False


###Sequential data types

####1. Strings

In [ ]:
x = 'hello' 
x = "hello" 
print(x, len(x))

hello 5


In [ ]:
# String operations
x = x + " world"
print(x)
print(x.upper())

hello world
HELLO WORLD


In [ ]:
# String indexing
print (x[0])
print (x[1])
print (x[-1])
print (x[-1])

h
e
d
d


####2. Lists

In [ ]:
x_list = [3, 1, 2]  
print(x_list, len(x_list))

[3, 1, 2] 3


In [ ]:
# List operations
x_list = x_list + [-1]
print(x_list)

[3, 1, 2, -1]


In [ ]:
# List indexing
print (x_list[0])
print (x_list[1])
print (x_list[-1])
print (x_list[-2])

3
1
-1
2


In [ ]:
#List assignment
x_list[1] = 'one'    
print(x_list)

[3, 'one', 2, -1]


In [ ]:
x ="hello"  # Strings aren't mutable only lists are
print (x)
#x[0] = 'i'
print (x)

hello
hello


More details: [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

####Sequence Slicing

Method to get slice of elements from list/string.

In [ ]:
x_list = list(range(5))    # range: built in function to return sequence of integers
print(x_list)      

[0, 1, 2, 3, 4]


In [ ]:
# Get slice from [inclusive index: exclusive index]

print(x_list[1:3]) 
print(x_list[1:]) 
print(x_list[1:-1]) 
print(x_list[:-1]) 
print(x_list)

[1, 2]
[1, 2, 3, 4]
[1, 2, 3]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]


####Sequence Looping

In [ ]:
# Using "in"

x_list = ["hello", "world"]

for x in x_list:
    print(x)

hello
world


In [ ]:
for x in x_list[0]:
  print (x)

TypeError: ignored

In [ ]:
for x in range(5):
  print (x)

0
1
2
3
4


####List comprehensions: Create new list based on existing list

In [ ]:
# y = x + 1

x_list = [0, 1, 2, 3, 4]


y_list = []
for x in x_list:
    y_list.append(x+1)
print(y_list)


[1, 2, 3, 4, 5]


In [ ]:
# List comprehension

x_list = [0, 1, 2, 3, 4]
y_list = [x+1 for x in x_list]
print(y_list)

[1, 2, 3, 4, 5]


In [ ]:
# List comprehension with conditionals
# y = x+1 if x%2==0 i.e. if x is even

x_list = [0, 1, 2, 3, 4]
y_list = [x+1 for x in x_list if x%2==0]
print(y_list)

[1, 3, 5]


###Functions

In [ ]:
def isEven(x, strReturn=False):
  ''' Return True if x is even else False
  '''
  isEven = x%2 == 0
  if strReturn:
    if isEven:
      retVal = 'TRUE'
    else:
      retVal = 'FALSE'
  else:
    retVal = isEven
  return retVal 

x_list = [0, 1, 2, 3, 4]
for x in x_list:
    print(x, isEven(x))

0 True
1 False
2 True
3 False
4 True


In [ ]:
x_list = [0, 1, 2, 3, 4]
a=[1,2,3]
b=[1,2,3]
c=a+b
print(c)
for x in x_list:
    print(x, isEven(x, strReturn=True))

[1, 2, 3, 1, 2, 3]
0 TRUE
1 FALSE
2 TRUE
3 FALSE
4 TRUE


# External Libraries

##Numpy

Numpy as an external library which serves as a backbone for most if not all machine learning libraries in python. It allows us to easily work with multidimentional array objects for fast numerical computations.

We need to first **import** numpy package to use it!

[Documentation](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [ ]:
import numpy as np

###Arrays

In [ ]:
a = np.array([1, 2, 3])  # 1D array
print(a)
print(type(a), a.shape)
print(a[0], a[1], a[2])

[1 2 3]
<class 'numpy.ndarray'> (3,)
1 2 3


In [ ]:
a[0] = -1     #Array indexing/assignment           
print(a)                  

[-1, 2, 3]


In [ ]:
b = np.array([[1,2,3], [4,5,6]])   # 2D array: (row, column)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(b[0, 0], b[0, 1], b[0, 2])

1 2 3


Additional functions to create arrays!

In [ ]:
a = np.zeros((2,2)) 
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((2,2)) 
print(b)

[[1. 1.]
 [1. 1.]]


In [ ]:
r = np.random.random((2,2))
print(r)

[[0.57124935 0.92667684]
 [0.00329098 0.76554907]]


Array Indexing




In [ ]:
a = np.arange(0, 1, 0.1) #np.arange(inclusive start, exclusive stop, delta)
print (a)
print (a[1:-1])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]


In [ ]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])   # 2D array
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(b[0, :])

[1 2 3]


Variable array Indexing

In [ ]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

In [ ]:
a = np.array([1, 0])
print(b[a, 1])

Boolean array indexing

In [ ]:
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b >=3)

In [ ]:
b_bool = b >= 2
print(b[b_bool])

##### Array Operations: Baseline operations are all element wise

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a + b)
print(np.add(a, b))

In [ ]:
print(a)
print(a+1)

In [ ]:
print(a * b)
print(np.multiply(a, b))

In [ ]:
print(np.exp(a))

##### Array Operations: Matrix

In [ ]:
a = np.array([[1,2]])
b = np.array([[1],[2]])
print(f'a.b:\n{a}.{b}\n')

print(a.dot(b))
print(np.dot(a, b))

##### Additional array [operations](https://numpy.org/doc/stable/reference/routines.math.html)

In [ ]:
a = np.array([[1,2], [3,4]])
print (a)

In [ ]:
print (np.sum(a))
print (a.sum())

In [ ]:
print (a.sum(axis=0))
print (a.sum(axis=1))

In [ ]:
print(a)
print(a.T) #Transpose

##### Reshaping

In [ ]:
a = np.array([1,2,3,4,5,6])
print (a)
print ()
print (a.reshape(2, -1))
print ()
print (a.reshape(-1, 2))

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([1,2,3,4,5,6])
print (a, a.shape)

a = a.T
print (a, a.shape)

In [ ]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(1, -1)
print (a, a.shape)

print ()
a = a.T
print (a, a.shape)

[[1 2 3 4 5 6]] (1, 6)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)


##Matplotlib: Plotting library

[documentation](https://matplotlib.org/3.5.1/index.html)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
#Display results inline here
#%matplotlib inline 

In [ ]:
x = np.arange(-10, 10, 0.1)
y = 1 / (1 + np.exp(x))

# Plot the points using matplotlib
plt.plot(x, y, label = 'exp line', color='r', ls='-.')

plt.xlabel("X")
plt.ylabel("Y")
plt.title("Example XY")
plt.legend()

# Assignment

In [ ]:
# 1. Row based addition I
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = np.array([0,0,1])
c = np.zeros(a.shape)
# Write a loop to add [b] to each row of [a] and assign to new array [c].
'''
 c =  [[1,2,3]  +   [[0,0,1]    = [[1,2,4],
       [4,5,6]]      [0,0,1]]      [4,5,7]]
'''
# START

d=b
b=np.concatenate((d,d))
b=b.reshape(2,-1)

for i in range(len(a)):
  for j in range(len(a[0])):
    c[i][j] = a[i][j] + b[i][j]
print(c)
# END

print((c==np.array([[1,2,4], [4,5,7]])).all())

[[1. 2. 4.]
 [4. 5. 7.]]
True


In [ ]:
# 2. Row based addition II. 
# Wihout a loop, add [b] to each row of [a] and assign to new array [c], by using [tile: https://numpy.org/doc/stable/reference/generated/numpy.tile.html] function
'''
 c =  [[1,2,3]  +   [[0,0,1]    = [[1,2,4],
       [4,5,6]]      [0,0,1]]      [4,5,7]]
'''
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = np.array([0,0,1])
c = np.zeros(a.shape)

# START
b = np.tile(b,reps=(2,1))
c= a + b
print(c)
# END

print((c==np.array([[1,2,4], [4,5,7]])).all())

[[1 2 4]
 [4 5 7]]
True


In [ ]:
''' 3. Write function to perform outer product [https://en.wikipedia.org/wiki/Outer_product] of vectors, [a] and [b] and assign it to [c]
    without using np.outer function with loops
'''

a = np.array([1,2,3])
b = np.array([4,5,6])

def getOuterProduct(x, y):
  # START
  product = np.zeros((x.shape[0], y.shape[0]))
  for i in range(len(a)):
    for j in range(len(b)):
      product[i,j]= a[i] * b[j]
  for k in product:
    print(k)
  #END

  return product

print((np.outer(a,b)==getOuterProduct(a, b)).all())

[4. 5. 6.]
[ 8. 10. 12.]
[12. 15. 18.]
True


In [1]:
''' 4. Write function to perform outer product [https://en.wikipedia.org/wiki/Outer_product] of vectors, [a] and [b] and assign it to [c]
    without using np.outer function and no loops. Hint: Use reshape, transpose and tile function or hstack/vstack functions.
'''
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

def getOuterProduct(x, y):
  # START
  product = np.zeros((x.shape[0], y.shape[0]))
  x = x.reshape(-1,1)
  y = y.reshape(1,-1)
  product = np.dot(x,y)
  print(product)

  #END
  return product
print((np.outer(a,b)==getOuterProduct(a, b)).all())

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
True
